name: Pull Request

env:
  CARGO_TERM_COLOR: always
  NEXTEST_RETRIES: 10

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-release
          path: target/release/redlib.exe
